### ISSUE TITLE
AssertionError With SQLAlchemy > 1.4

### ISSUE THREAD

**Issue by tataraba** [bprinty/Flask-Occam#30]
I encountered the following error after updating to SQLAlchemy 1.45:

```AssertionError: Associated User model must be named `User` or defined with __user_model__ property!```

Downgrading to SQLAlchemy 1.3 fixes the issue. Seems like the declarative system changed as of 1.4. I noticed that this same issue happened with Flask-Authorize but was fixed with the latest release. Looks like the way that classes are retrieved needs to change. 

I patched in a fix on my local copy of Occam to emulate the fix for Authorize.

Here is piece that needs to change (converters.py):

https://github.com/bprinty/Flask-Occam/blob/d83cb41e529fa6437f2421ed69ed7984e5d54ed9/flask_occam/converters.py#L28

I updated this:
```
db = current_app.extensions['sqlalchemy'].db
for cls in db.Model._decl_class_registry.values():
```
To this:
```
db = current_app.extensions['sqlalchemy'].db
registry = class_registry(db.Model)   
for cls in registry.values():
```

Not sure if there are any other downstream effects, but this seems to have fixed my issue.

**Comment by bprinty** [comment]
Thanks for the heads up! I just added a fix and created a new release (`0.2.1`).
